# ==========================================
# Application
# ==========================================
spring.application.name=fitness-gym-api
server.port=2222
server.servlet.context-path=/api/v1
# ==========================================
# Oracle Database
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=SYSTEM
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


# ==========================================
# JWT
# ==========================================

app.security.jwt.secret=CGx46ZG58j1640J//0KQZ7AVVkFyebbgFmWhhevBfNPk=

app.security.jwt.access-token-expiration=900000

app.security.jwt.refresh-token-expiration=604800000


# ==========================================
# LOGGING
# ==========================================

logging.level.org.springframework.security=INFO

logging.level.com.fitnessgym.api=DEBUG